# Site settings
title: Jeff Janko.ws/ki
email: me@jeffjanko.ws

# Description will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  A blog created for the sole purpose of personal posterity. 
  My memory is utter crap, and therefore I need an archive of sorts.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffjanko.ws" # the base hostname & protocol for your site
permalink: /ki/:year/:month/:day/:title/

#twitter_username: jekyllrb
github_username:  JeffJankowski

# Build settings
markdown: kramdown
highlighter: pygments 

gems:
  - jekyll-redirect-from